
const ActionTypes = {
  SERVICE_SEARCH_GIF: 'SERVICE_SEARCH_GIF',
  LOAD_GIFS: 'LOAD_GIFS',
  SET_ERROR_LOADING_GIFS: 'SET_ERROR_LOADING_GIFS',
  SERVICE_SAVE_SEARCH_GIF: 'SERVICE_SAVE_SEARCH_GIF',
  SAVE_SEARCH_GIF: 'SAVE_SEARCH_GIF',
  SERVICE_LOAD_SEARCH_GIF_HISTORY: 'SERVICE_LOAD_SEARCH_GIF_HISTORY'
};

export default ActionTypes;
